/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package gui;

import estruturas.GrafoBasico;
import estruturas.algoritmos.grafos.basico.BuscaLargura;
import gui.desenho.estruturas.GrafoAnotado;
import java.util.Map.Entry;
import javax.swing.table.DefaultTableModel;

/**
 * Diálogo para exibição da tabela da busca em largura.
 * 
 * @author David Buzatto
 */
public class DialogTabelaBFS extends javax.swing.JDialog {

    private GrafoBasico grafo;
    private GrafoAnotado grafoAnt;
    private BuscaLargura bfs;
    private DefaultTableModel modelo;
    
    /**
     * Creates new form DialogRemoverArestaGrafo
     */
    public DialogTabelaBFS( java.awt.Frame parent, boolean modal, 
            GrafoBasico grafo, GrafoAnotado grafoAnt, BuscaLargura bfs ) {
        
        super( parent, modal );
        initComponents();
        
        this.grafo = grafo;
        this.grafoAnt = grafoAnt;
        this.bfs = bfs;
        
        modelo = new DefaultTableModel( new String[]{
            "v",
            "marcado[v]",
            "arestaAte[v]",
            "distanciaAte[v]"
        }, 0 );
        
        boolean[] marcado = bfs.getMarcado();
        int[] arestaAte = bfs.getArestaAte();
        int[] distanciaAte = bfs.getDistanciaAte();
        
        for ( int i = 0; i < marcado.length; i++ ) {
            
            modelo.addRow( new String[]{
                String.valueOf( grafoAnt.getTransicaoGrafoParaAnotado().get( i ) ), 
                marcado[i] ? "<html><font color=\"#0070C0\">T</font></html>" : "F", 
                arestaAte[i] == -1 ? "-" : String.valueOf( grafoAnt.getTransicaoGrafoParaAnotado().get( arestaAte[i] ) ),
                distanciaAte[i] == -1 ? "-" : String.valueOf( distanciaAte[i] )
            });
        }
        
        tabela.setModel( modelo );
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings( "unchecked" )
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sp = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        btnOk = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tabela BFS");

        tabela.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        sp.setViewportView(tabela);

        btnOk.setText("OK");
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sp, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnOk)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sp, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnOk)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(488, 364));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
        dispose();
    }//GEN-LAST:event_btnOkActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOk;
    private javax.swing.JScrollPane sp;
    private javax.swing.JTable tabela;
    // End of variables declaration//GEN-END:variables
}
