/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package gui;

import estruturas.Fila;
import estruturas.excecoes.EmptyQueueException;
import gui.desenho.PainelDesenho;
import gui.desenho.estruturas.FilaDesenhavel;
import javax.swing.JOptionPane;

/**
 * Janela para a simulação de filas.
 * 
 * @author David Buzatto
 */
public class IFFila extends javax.swing.JInternalFrame {

    private Fila<String> fila;
    private FilaDesenhavel filaD;
    
    /**
     * Creates new form IFFila
     */
    public IFFila() {
        
        fila = new Fila<>();
        filaD = new FilaDesenhavel( fila );
        
        initComponents();
        setVisible( true );
        
        filaD.setPainel( painelDesenho );
        
        fieldCabeca.setText( "vazio" );
        fieldTamanho.setText( String.valueOf( fila.getTamanho() ) );
        painelDesenho.repaint();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings( "unchecked" )
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelDesenho = new PainelDesenho( filaD );
        painelOperacoes = new javax.swing.JPanel();
        labelValor = new javax.swing.JLabel();
        labelDesenfileirou = new javax.swing.JLabel();
        fieldValor = new javax.swing.JTextField();
        fieldDesenfileirou = new javax.swing.JTextField();
        btnEnfileirar = new javax.swing.JButton();
        btnDesenfileirar = new javax.swing.JButton();
        btnEsvaziar = new javax.swing.JButton();
        painelDados = new javax.swing.JPanel();
        labelCabeca = new javax.swing.JLabel();
        labelTamanho = new javax.swing.JLabel();
        fieldCabeca = new javax.swing.JTextField();
        fieldTamanho = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Fila");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/imagens/filaP.png"))); // NOI18N

        javax.swing.GroupLayout painelDesenhoLayout = new javax.swing.GroupLayout(painelDesenho);
        painelDesenho.setLayout(painelDesenhoLayout);
        painelDesenhoLayout.setHorizontalGroup(
            painelDesenhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 340, Short.MAX_VALUE)
        );
        painelDesenhoLayout.setVerticalGroup(
            painelDesenhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        painelOperacoes.setBorder(javax.swing.BorderFactory.createTitledBorder("Operações"));

        labelValor.setText("Valor:");

        labelDesenfileirou.setText("Desenfileirou:");

        fieldValor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldValorActionPerformed(evt);
            }
        });

        fieldDesenfileirou.setEditable(false);

        btnEnfileirar.setText("Enfileirar");
        btnEnfileirar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnfileirarActionPerformed(evt);
            }
        });

        btnDesenfileirar.setText("Desenfileirar");
        btnDesenfileirar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDesenfileirarActionPerformed(evt);
            }
        });

        btnEsvaziar.setText("Esvaziar");
        btnEsvaziar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEsvaziarActionPerformed(evt);
            }
        });

        painelDados.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados da Estrutura"));

        labelCabeca.setText("Cabeça:");

        labelTamanho.setText("Tamanho:");

        fieldCabeca.setEditable(false);

        fieldTamanho.setEditable(false);

        javax.swing.GroupLayout painelDadosLayout = new javax.swing.GroupLayout(painelDados);
        painelDados.setLayout(painelDadosLayout);
        painelDadosLayout.setHorizontalGroup(
            painelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelDadosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelTamanho)
                    .addComponent(labelCabeca))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fieldCabeca)
                    .addComponent(fieldTamanho))
                .addContainerGap())
        );
        painelDadosLayout.setVerticalGroup(
            painelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelDadosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCabeca)
                    .addComponent(fieldCabeca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTamanho)
                    .addComponent(fieldTamanho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(114, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout painelOperacoesLayout = new javax.swing.GroupLayout(painelOperacoes);
        painelOperacoes.setLayout(painelOperacoesLayout);
        painelOperacoesLayout.setHorizontalGroup(
            painelOperacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelOperacoesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelOperacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelOperacoesLayout.createSequentialGroup()
                        .addGroup(painelOperacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelDesenfileirou)
                            .addComponent(labelValor))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(painelOperacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fieldValor)
                            .addComponent(fieldDesenfileirou)))
                    .addComponent(painelDados, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelOperacoesLayout.createSequentialGroup()
                        .addGap(0, 71, Short.MAX_VALUE)
                        .addGroup(painelOperacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnEnfileirar, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnDesenfileirar, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnEsvaziar, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        painelOperacoesLayout.setVerticalGroup(
            painelOperacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelOperacoesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelOperacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelValor)
                    .addComponent(fieldValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEnfileirar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelOperacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDesenfileirou)
                    .addComponent(fieldDesenfileirou, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDesenfileirar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEsvaziar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painelDados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(painelDesenho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painelOperacoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelOperacoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(painelDesenho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEnfileirarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnfileirarActionPerformed
        enfileirar();
    }//GEN-LAST:event_btnEnfileirarActionPerformed

    private void btnDesenfileirarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDesenfileirarActionPerformed
        
        try {
            fieldDesenfileirou.setText( fila.desenfileirar());
            if ( !fila.estaVazia() ) {
                fieldCabeca.setText( fila.consultarCabeca() );
            } else {
                fieldCabeca.setText( "vazio" );
            }
            fieldTamanho.setText( String.valueOf( fila.getTamanho() ) );
            painelDesenho.repaint();
        } catch ( EmptyQueueException exc ) {
            fieldDesenfileirou.setText( "" );
            fieldCabeca.setText( "vazio" );
            fieldTamanho.setText( String.valueOf( fila.getTamanho() ) );
            painelDesenho.repaint();
            JOptionPane.showMessageDialog( this, "Fila vazia.", 
                    "Aviso", JOptionPane.WARNING_MESSAGE );
        }
        
    }//GEN-LAST:event_btnDesenfileirarActionPerformed

    private void btnEsvaziarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEsvaziarActionPerformed
        
        fila.esvaziar();
        fieldValor.setText( "" );
        fieldDesenfileirou.setText( "" );
        fieldCabeca.setText( "vazio" );
        fieldTamanho.setText( String.valueOf( fila.getTamanho() ) );
        
        painelDesenho.repaint();
        
    }//GEN-LAST:event_btnEsvaziarActionPerformed

    private void fieldValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldValorActionPerformed
        enfileirar();
    }//GEN-LAST:event_fieldValorActionPerformed

    private void enfileirar() {
        
        fila.enfileirar(fieldValor.getText() );
        fieldValor.setText( "" );
        fieldDesenfileirou.setText( "" );
        fieldCabeca.setText( fila.consultarCabeca() );
        fieldTamanho.setText( String.valueOf( fila.getTamanho() ) );
        
        fieldValor.requestFocus();
        
        painelDesenho.repaint();
        
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDesenfileirar;
    private javax.swing.JButton btnEnfileirar;
    private javax.swing.JButton btnEsvaziar;
    private javax.swing.JTextField fieldCabeca;
    private javax.swing.JTextField fieldDesenfileirou;
    private javax.swing.JTextField fieldTamanho;
    private javax.swing.JTextField fieldValor;
    private javax.swing.JLabel labelCabeca;
    private javax.swing.JLabel labelDesenfileirou;
    private javax.swing.JLabel labelTamanho;
    private javax.swing.JLabel labelValor;
    private javax.swing.JPanel painelDados;
    private javax.swing.JPanel painelDesenho;
    private javax.swing.JPanel painelOperacoes;
    // End of variables declaration//GEN-END:variables
}
