/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package gui;

import estruturas.Grafo;
import estruturas.algoritmos.grafos.AlgoritmosBasicosGrafo;
import estruturas.algoritmos.grafos.ComponentesConexos;
import gui.desenho.PainelDesenho;
import gui.desenho.estruturas.GrafoAnotado;
import gui.desenho.estruturas.GrafoDesenhavel;
import gui.desenho.estruturas.VerticeGrafo;
import java.awt.Point;
import java.util.Map.Entry;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 * Janela para a simulação de grafos.
 * 
 * @author David Buzatto
 */
public class IFGrafo extends javax.swing.JInternalFrame {

    private GrafoDesenhavel grafoD;
    private GrafoAnotado grafoAnt;
    private Grafo grafo;
    private boolean movendo;
    private VerticeGrafo verticeMovimento;
    private VerticeGrafo verticeRemocao;
    private int tamanhoVertice = 40;
    private int deslocamentoX;
    private int deslocamentoY;
    
    /**
     * Creates new form IFArvoreBinariaBusca
     */
    public IFGrafo() {
        
        grafoAnt = new GrafoAnotado();
        
        
        
        
        // código para testes...
        grafoAnt.adicionarVertice( 100, 100, tamanhoVertice );
        grafoAnt.adicionarVertice( 150, 200, tamanhoVertice );
        grafoAnt.adicionarVertice( 250, 200, tamanhoVertice );
        grafoAnt.adicionarVertice( 200, 300, tamanhoVertice );
        grafoAnt.adicionarVertice( 300, 300, tamanhoVertice );
        grafoAnt.adicionarVertice( 100, 400, tamanhoVertice );
        grafoAnt.adicionarVertice( 350, 200, tamanhoVertice );
        grafoAnt.adicionarVertice( 450, 150, tamanhoVertice );
        grafoAnt.adicionarVertice( 550, 150, tamanhoVertice );
        grafoAnt.adicionarVertice( 450, 250, tamanhoVertice );
        grafoAnt.adicionarVertice( 550, 250, tamanhoVertice );
        grafoAnt.adicionarVertice( 450, 350, tamanhoVertice );
        grafoAnt.adicionarVertice( 550, 350, tamanhoVertice );
        
        grafoAnt.adicionarAresta( 0, 5 );
        grafoAnt.adicionarAresta( 4, 3 );
        grafoAnt.adicionarAresta( 0, 1 );
        grafoAnt.adicionarAresta( 9, 12 );
        grafoAnt.adicionarAresta( 6, 4 );
        grafoAnt.adicionarAresta( 5, 4 );
        grafoAnt.adicionarAresta( 0, 2 );
        grafoAnt.adicionarAresta( 11, 12 );
        grafoAnt.adicionarAresta( 9, 10 );
        grafoAnt.adicionarAresta( 0, 6 );
        grafoAnt.adicionarAresta( 7, 8 );
        grafoAnt.adicionarAresta( 9, 11 );
        grafoAnt.adicionarAresta( 5, 3 );
        
        grafo = grafoAnt.gerarGrafo();
        
        ComponentesConexos cc = new ComponentesConexos( grafo );
        System.out.println( cc.quantidade() );
        
        // fim do código para testes
        
        
        
        
        
        grafoD = new GrafoDesenhavel( grafoAnt );
        
        initComponents();
        setVisible( true );
        
        grafoD.setPainel( painelDesenho );
        painelDesenho.repaint();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings( "unchecked" )
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuPopUp = new javax.swing.JPopupMenu();
        itemMenuRemover = new javax.swing.JMenuItem();
        painelDesenho = new PainelDesenho( grafoD );
        painelOperacoes = new javax.swing.JPanel();
        tbtnNovoVertice = new javax.swing.JToggleButton();
        tbtnNovaAresta = new javax.swing.JToggleButton();
        painelAlgoritmos = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        painelDados = new javax.swing.JPanel();
        labelV = new javax.swing.JLabel();
        labelA = new javax.swing.JLabel();
        labelGM = new javax.swing.JLabel();
        labelGMX = new javax.swing.JLabel();
        fieldV = new javax.swing.JTextField();
        fieldA = new javax.swing.JTextField();
        fieldGM = new javax.swing.JTextField();
        fieldGMX = new javax.swing.JTextField();

        itemMenuRemover.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/imagens/delete.png"))); // NOI18N
        itemMenuRemover.setText("remover");
        itemMenuRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuRemoverActionPerformed(evt);
            }
        });
        menuPopUp.add(itemMenuRemover);

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Grafo");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/imagens/grafoP.png"))); // NOI18N

        painelDesenho.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                painelDesenhoMouseDragged(evt);
            }
        });
        painelDesenho.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                painelDesenhoMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                painelDesenhoMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout painelDesenhoLayout = new javax.swing.GroupLayout(painelDesenho);
        painelDesenho.setLayout(painelDesenhoLayout);
        painelDesenhoLayout.setHorizontalGroup(
            painelDesenhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 674, Short.MAX_VALUE)
        );
        painelDesenhoLayout.setVerticalGroup(
            painelDesenhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        painelOperacoes.setBorder(javax.swing.BorderFactory.createTitledBorder("Operações"));

        tbtnNovoVertice.setText("Novo Vértice");
        tbtnNovoVertice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbtnNovoVerticeActionPerformed(evt);
            }
        });

        tbtnNovaAresta.setText("Nova Aresta");
        tbtnNovaAresta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbtnNovaArestaActionPerformed(evt);
            }
        });

        painelAlgoritmos.setBorder(javax.swing.BorderFactory.createTitledBorder("Algoritmos"));

        jLabel1.setText("Fonte:");

        jButton1.setText("Tabela DFS");

        jButton2.setText("DFS");

        jButton3.setText("Tabela BFS");

        jButton4.setText("BFS");

        jLabel2.setText("Caminho Até:");

        jButton5.setText("Mostrar Caminho");

        jButton6.setText("Limpar");

        jButton7.setText("Identificar C. Conexos");

        javax.swing.GroupLayout painelAlgoritmosLayout = new javax.swing.GroupLayout(painelAlgoritmos);
        painelAlgoritmos.setLayout(painelAlgoritmosLayout);
        painelAlgoritmosLayout.setHorizontalGroup(
            painelAlgoritmosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelAlgoritmosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelAlgoritmosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelAlgoritmosLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1))
                    .addGroup(painelAlgoritmosLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelAlgoritmosLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(painelAlgoritmosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelAlgoritmosLayout.createSequentialGroup()
                                .addComponent(jButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelAlgoritmosLayout.createSequentialGroup()
                                .addComponent(jButton4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton3))
                            .addComponent(jButton5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton6, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton7, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        painelAlgoritmosLayout.setVerticalGroup(
            painelAlgoritmosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelAlgoritmosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelAlgoritmosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelAlgoritmosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelAlgoritmosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painelAlgoritmosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        painelDados.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados da Estrutura"));

        labelV.setText("Vértices:");

        labelA.setText("Arestas:");

        labelGM.setText("Grau Médio:");

        labelGMX.setText("Grau Máximo:");

        fieldV.setEditable(false);

        fieldA.setEditable(false);

        fieldGM.setEditable(false);

        fieldGMX.setEditable(false);

        javax.swing.GroupLayout painelDadosLayout = new javax.swing.GroupLayout(painelDados);
        painelDados.setLayout(painelDadosLayout);
        painelDadosLayout.setHorizontalGroup(
            painelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelDadosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelGMX)
                    .addComponent(labelGM)
                    .addComponent(labelA)
                    .addComponent(labelV))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fieldV)
                    .addComponent(fieldA)
                    .addComponent(fieldGM)
                    .addComponent(fieldGMX))
                .addContainerGap())
        );
        painelDadosLayout.setVerticalGroup(
            painelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelDadosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelV)
                    .addComponent(fieldV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelA)
                    .addComponent(fieldA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelGM)
                    .addComponent(fieldGM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelGMX)
                    .addComponent(fieldGMX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(123, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout painelOperacoesLayout = new javax.swing.GroupLayout(painelOperacoes);
        painelOperacoes.setLayout(painelOperacoesLayout);
        painelOperacoesLayout.setHorizontalGroup(
            painelOperacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelOperacoesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelOperacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(painelDados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(painelAlgoritmos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(painelOperacoesLayout.createSequentialGroup()
                        .addComponent(tbtnNovoVertice)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tbtnNovaAresta)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        painelOperacoesLayout.setVerticalGroup(
            painelOperacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelOperacoesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelOperacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tbtnNovaAresta)
                    .addComponent(tbtnNovoVertice))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painelAlgoritmos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painelDados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(painelDesenho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painelOperacoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelOperacoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(painelDesenho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemMenuRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuRemoverActionPerformed

        grafoAnt.removerVertice( verticeRemocao.v );
        grafo = grafoAnt.gerarGrafo();
        
        fieldV.setText( String.valueOf( grafo.v() ) );
        fieldA.setText( String.valueOf( grafo.e() ) );
        fieldGM.setText( String.valueOf( 
                        (double) Math.round( AlgoritmosBasicosGrafo.grauMedio( grafo ) * 1000 ) / 1000 ) );
        fieldGMX.setText( String.valueOf( AlgoritmosBasicosGrafo.grauMaximo(grafo ) ) );
        
        painelDesenho.repaint();
            
        JOptionPane.showMessageDialog( painelDesenho,
            String.format( "O vértice \"%d\" foi removido.",
                verticeRemocao.v ), "Removido", JOptionPane.INFORMATION_MESSAGE );
        
        verticeRemocao = null;
        
    }//GEN-LAST:event_itemMenuRemoverActionPerformed

    private void painelDesenhoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_painelDesenhoMouseReleased
        movendo = false;
        verticeMovimento = null;
    }//GEN-LAST:event_painelDesenhoMouseReleased

    private void painelDesenhoMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_painelDesenhoMouseDragged
        
        if ( movendo ) {
            
            verticeMovimento.xCentro = evt.getX() - deslocamentoX;
            verticeMovimento.yCentro = evt.getY() - deslocamentoY;
            verticeMovimento.xIni = verticeMovimento.xCentro - verticeMovimento.tamanho / 2;
            verticeMovimento.yIni = verticeMovimento.yCentro - verticeMovimento.tamanho / 2;
            verticeMovimento.xFim = verticeMovimento.xIni + verticeMovimento.tamanho;
            verticeMovimento.yFim = verticeMovimento.yIni + verticeMovimento.tamanho;
            painelDesenho.repaint();
            
        }
        
    }//GEN-LAST:event_painelDesenhoMouseDragged

    private void painelDesenhoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_painelDesenhoMousePressed
        
        if ( SwingUtilities.isLeftMouseButton( evt ) ) {

            if ( tbtnNovoVertice.isSelected() ) {
                
                grafoAnt.adicionarVertice( evt.getX(), evt.getY(), tamanhoVertice );
                grafo = grafoAnt.gerarGrafo();
                
                fieldV.setText( String.valueOf( grafo.v() ) );
                fieldA.setText( String.valueOf( grafo.e() ) );
                fieldGM.setText( String.valueOf( 
                        (double) Math.round( AlgoritmosBasicosGrafo.grauMedio( grafo ) * 1000 ) / 1000 ) );
                fieldGMX.setText( String.valueOf( AlgoritmosBasicosGrafo.grauMaximo(grafo ) ) );
        
            } else if ( tbtnNovaAresta.isSelected() ) {
                
                grafo = grafoAnt.gerarGrafo();
                
                fieldV.setText( String.valueOf( grafo.v() ) );
                fieldA.setText( String.valueOf( grafo.e() ) );
                fieldGM.setText( String.valueOf( 
                        (double) Math.round( AlgoritmosBasicosGrafo.grauMedio( grafo ) * 1000 ) / 1000 ) );
                fieldGMX.setText( String.valueOf( AlgoritmosBasicosGrafo.grauMaximo(grafo ) ) );
                
            } else {
                
                for ( Entry<Integer, VerticeGrafo> v : grafoAnt.getVertices().entrySet() ) {
                    
                    Point p = evt.getPoint();
                
                    int cat1 = p.x - v.getValue().xCentro;
                    int cat2 = p.y - v.getValue().yCentro;

                    if ( cat1 * cat1 + cat2 * cat2 <= tamanhoVertice * tamanhoVertice / 2 ) {

                        movendo = true;
                        verticeMovimento = v.getValue();
                        
                        deslocamentoX = cat1;
                        deslocamentoY = cat2;
                        
                        break;
                        
                    }
                    
                }
                
            }
            
        } else if ( SwingUtilities.isRightMouseButton( evt ) ) {
            
            tbtnNovoVertice.setSelected( false );
            tbtnNovaAresta.setSelected( false );
            
            for ( Entry<Integer, VerticeGrafo> v : grafoAnt.getVertices().entrySet() ) {
                    
                Point p = evt.getPoint();

                int cat1 = p.x - v.getValue().xCentro;
                int cat2 = p.y - v.getValue().yCentro;

                if ( cat1 * cat1 + cat2 * cat2 <= tamanhoVertice * tamanhoVertice / 2 ) {

                    verticeRemocao = v.getValue();
                    itemMenuRemover.setText( String.format( "Remover vértice \"%d\"", verticeRemocao.v ) );
                    menuPopUp.show( painelDesenho, p.x, p.y );

                    break;

                }

            }
            
        }
        
        painelDesenho.repaint();
        
    }//GEN-LAST:event_painelDesenhoMousePressed

    private void tbtnNovoVerticeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbtnNovoVerticeActionPerformed
        tbtnNovaAresta.setSelected( false );
    }//GEN-LAST:event_tbtnNovoVerticeActionPerformed

    private void tbtnNovaArestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbtnNovaArestaActionPerformed
        tbtnNovoVertice.setSelected( false );
    }//GEN-LAST:event_tbtnNovaArestaActionPerformed
           
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField fieldA;
    private javax.swing.JTextField fieldGM;
    private javax.swing.JTextField fieldGMX;
    private javax.swing.JTextField fieldV;
    private javax.swing.JMenuItem itemMenuRemover;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel labelA;
    private javax.swing.JLabel labelGM;
    private javax.swing.JLabel labelGMX;
    private javax.swing.JLabel labelV;
    private javax.swing.JPopupMenu menuPopUp;
    private javax.swing.JPanel painelAlgoritmos;
    private javax.swing.JPanel painelDados;
    private javax.swing.JPanel painelDesenho;
    private javax.swing.JPanel painelOperacoes;
    private javax.swing.JToggleButton tbtnNovaAresta;
    private javax.swing.JToggleButton tbtnNovoVertice;
    // End of variables declaration//GEN-END:variables
}
