/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package gui;

import estruturas.HeapMinimo;
import estruturas.excecoes.EmptyHeapException;
import gui.desenho.PainelDesenho;
import gui.desenho.estruturas.HeapMinimoAnotado;
import gui.desenho.estruturas.HeapMinimoDesenhavel;
import javax.swing.JOptionPane;

/**
 * Janela para a simulação de heaps mínimos.
 * 
 * @author David Buzatto
 */
public class IFHeapMinimo extends javax.swing.JInternalFrame {

    private HeapMinimo<Integer> hm;
    private HeapMinimoDesenhavel<Integer> hmD;
    private HeapMinimoAnotado<Integer> hmAnt;
    private PainelDesenho painelD;
    
    /**
     * Creates new form IFArvoreBinariaBusca
     */
    public IFHeapMinimo() {
        
        hm = new HeapMinimo<>();
        hmD = new HeapMinimoDesenhavel<>( hm );
        hmAnt = new HeapMinimoAnotado<>( hm );
        
        initComponents();
        setVisible( true );
        
        painelD = (PainelDesenho) painelDesenho;
        
        hmD.setPainel( painelD );
        
        fieldMinimo.setText( "vazio" );
        fieldTamanho.setText( String.valueOf( hm.getTamanho() ) );
        painelD.repaint();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings( "unchecked" )
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroup = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        painelDesenho = new PainelDesenho( hmD );
        painelOperacoes = new javax.swing.JPanel();
        labelValor = new javax.swing.JLabel();
        labelRemovido = new javax.swing.JLabel();
        fieldValor = new javax.swing.JTextField();
        fieldRemovido = new javax.swing.JTextField();
        btnInserir = new javax.swing.JButton();
        btnRemover = new javax.swing.JButton();
        btnEsvaziar = new javax.swing.JButton();
        painelDados = new javax.swing.JPanel();
        labelMinimo = new javax.swing.JLabel();
        labelTamanho = new javax.swing.JLabel();
        fieldMinimo = new javax.swing.JTextField();
        fieldTamanho = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Heap Mínimo");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/imagens/heapMinimoP.png"))); // NOI18N

        javax.swing.GroupLayout painelDesenhoLayout = new javax.swing.GroupLayout(painelDesenho);
        painelDesenho.setLayout(painelDesenhoLayout);
        painelDesenhoLayout.setHorizontalGroup(
            painelDesenhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 514, Short.MAX_VALUE)
        );
        painelDesenhoLayout.setVerticalGroup(
            painelDesenhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 570, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(painelDesenho);

        painelOperacoes.setBorder(javax.swing.BorderFactory.createTitledBorder("Operações"));

        labelValor.setText("Valor:");

        labelRemovido.setText("Removido:");

        fieldValor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldValorActionPerformed(evt);
            }
        });

        fieldRemovido.setEditable(false);

        btnInserir.setText("Inserir");
        btnInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInserirActionPerformed(evt);
            }
        });

        btnRemover.setText("Remover");
        btnRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverActionPerformed(evt);
            }
        });

        btnEsvaziar.setText("Esvaziar");
        btnEsvaziar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEsvaziarActionPerformed(evt);
            }
        });

        painelDados.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados da Estrutura"));

        labelMinimo.setText("Mínimo:");

        labelTamanho.setText("Tamanho:");

        fieldMinimo.setEditable(false);

        fieldTamanho.setEditable(false);

        javax.swing.GroupLayout painelDadosLayout = new javax.swing.GroupLayout(painelDados);
        painelDados.setLayout(painelDadosLayout);
        painelDadosLayout.setHorizontalGroup(
            painelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelDadosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelTamanho)
                    .addComponent(labelMinimo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fieldMinimo, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                    .addComponent(fieldTamanho))
                .addContainerGap())
        );
        painelDadosLayout.setVerticalGroup(
            painelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelDadosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelMinimo)
                    .addComponent(fieldMinimo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTamanho)
                    .addComponent(fieldTamanho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout painelOperacoesLayout = new javax.swing.GroupLayout(painelOperacoes);
        painelOperacoes.setLayout(painelOperacoesLayout);
        painelOperacoesLayout.setHorizontalGroup(
            painelOperacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelOperacoesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelOperacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelOperacoesLayout.createSequentialGroup()
                        .addGroup(painelOperacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelRemovido)
                            .addComponent(labelValor))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(painelOperacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fieldValor)
                            .addComponent(fieldRemovido)))
                    .addComponent(painelDados, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelOperacoesLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(painelOperacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnInserir, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnRemover, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnEsvaziar, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        painelOperacoesLayout.setVerticalGroup(
            painelOperacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelOperacoesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelOperacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelValor)
                    .addComponent(fieldValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnInserir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelOperacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelRemovido)
                    .addComponent(fieldRemovido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRemover)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEsvaziar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painelDados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painelOperacoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 529, Short.MAX_VALUE)
            .addComponent(painelOperacoes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fieldValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldValorActionPerformed
        inserir();
    }//GEN-LAST:event_fieldValorActionPerformed

    private void btnInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInserirActionPerformed
        inserir();
    }//GEN-LAST:event_btnInserirActionPerformed

    private void btnRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverActionPerformed

        try {
            
            fieldRemovido.setText( String.valueOf( hm.remover() ) );
            
            hmAnt = new HeapMinimoAnotado<>( hm );
            hmD.setAbbAnt( hmAnt );
            
            if ( !hm.estaVazia() ) {
                fieldMinimo.setText( String.valueOf( hm.consultar() ) );
            } else {
                fieldMinimo.setText( "vazio" );
            }
            
            fieldTamanho.setText( String.valueOf( hm.getTamanho() ) );
            painelDesenho.repaint();
            
        } catch ( EmptyHeapException exc ) {
            
            fieldRemovido.setText( "" );
            fieldMinimo.setText( "vazio" );
            fieldTamanho.setText( String.valueOf( hm.getTamanho() ) );
            painelDesenho.repaint();
            
            JOptionPane.showMessageDialog( this, "Heap mínimo vazio.",
                "Aviso", JOptionPane.WARNING_MESSAGE );
            
        }

    }//GEN-LAST:event_btnRemoverActionPerformed

    private void btnEsvaziarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEsvaziarActionPerformed

        hm.esvaziar();
        fieldValor.setText( "" );
        fieldRemovido.setText( "" );
        fieldMinimo.setText( "vazio" );
        fieldTamanho.setText( String.valueOf( hm.getTamanho() ) );

        hmAnt = new HeapMinimoAnotado<>( hm );
        hmD.setAbbAnt( hmAnt );
            
        painelDesenho.repaint();

    }//GEN-LAST:event_btnEsvaziarActionPerformed

    private void inserir() {
        
        try {
            
            hm.inserir( Integer.valueOf( fieldValor.getText() ) );
            hmAnt = new HeapMinimoAnotado<>( hm );
            hmD.setAbbAnt( hmAnt );

            fieldValor.setText( "" );
            fieldRemovido.setText( "" );
            fieldMinimo.setText( String.valueOf( hm.consultar() ) );
            fieldTamanho.setText( String.valueOf( hm.getTamanho() ) );
            
        } catch ( NumberFormatException exc ) {
            
            JOptionPane.showMessageDialog( this, "Entre com um número inteiro!", "ERRO", JOptionPane.ERROR_MESSAGE );
            fieldValor.setSelectionStart( 0 );
            fieldValor.setSelectionEnd( fieldValor.getText().length() );
            
        }
        
        fieldValor.requestFocus();
        
        painelD.repaint();
        
    }
           
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEsvaziar;
    private javax.swing.ButtonGroup btnGroup;
    private javax.swing.JButton btnInserir;
    private javax.swing.JButton btnRemover;
    private javax.swing.JTextField fieldMinimo;
    private javax.swing.JTextField fieldRemovido;
    private javax.swing.JTextField fieldTamanho;
    private javax.swing.JTextField fieldValor;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelMinimo;
    private javax.swing.JLabel labelRemovido;
    private javax.swing.JLabel labelTamanho;
    private javax.swing.JLabel labelValor;
    private javax.swing.JPanel painelDados;
    private javax.swing.JPanel painelDesenho;
    private javax.swing.JPanel painelOperacoes;
    // End of variables declaration//GEN-END:variables
}
