/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package gui;

import estruturas.Lista;
import estruturas.excecoes.EmptyListException;
import gui.desenho.PainelDesenho;
import gui.desenho.estruturas.ListaDesenhavel;
import java.awt.Point;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 * Janela para a simulação de listas.
 * 
 * @author David Buzatto
 */
public class IFLista extends javax.swing.JInternalFrame {

    private Lista<String> lista;
    private ListaDesenhavel listaD;
    private AreaItemLista item; // item que receberá a ação de remover ou inserir
    
    /**
     * Creates new form IFLista
     */
    public IFLista() {
        
        lista = new Lista<>();
        listaD = new ListaDesenhavel( lista );
        
        initComponents();
        setVisible( true );
        
        listaD.setPainel( painelDesenho );
        
        fieldInicio.setText( "vazio" );
        fieldFim.setText( "vazio" );
        fieldTamanho.setText( String.valueOf( lista.getTamanho() ) );
        painelDesenho.repaint();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings( "unchecked" )
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuPopUp = new javax.swing.JPopupMenu();
        itemMenuInserirPosicao = new javax.swing.JMenuItem();
        itemMenuInserirDireita = new javax.swing.JMenuItem();
        separador = new javax.swing.JPopupMenu.Separator();
        itemMenuRemover = new javax.swing.JMenuItem();
        painelDesenho = new PainelDesenho( listaD );
        painelOperacoes = new javax.swing.JPanel();
        labelValorInicio = new javax.swing.JLabel();
        labelValorFim = new javax.swing.JLabel();
        labelRemoveuInicio = new javax.swing.JLabel();
        labelRemoveuFim = new javax.swing.JLabel();
        fieldValorInicio = new javax.swing.JTextField();
        fieldValorFim = new javax.swing.JTextField();
        fieldRemoveuInicio = new javax.swing.JTextField();
        fieldRemoveuFim = new javax.swing.JTextField();
        btnInserirInicio = new javax.swing.JButton();
        btnInserirFim = new javax.swing.JButton();
        btnRemoverInicio = new javax.swing.JButton();
        btnRemoverFim = new javax.swing.JButton();
        btnEsvaziar = new javax.swing.JButton();
        painelDados = new javax.swing.JPanel();
        labelInicio = new javax.swing.JLabel();
        labelFim = new javax.swing.JLabel();
        labelTamanho = new javax.swing.JLabel();
        fieldInicio = new javax.swing.JTextField();
        fieldFim = new javax.swing.JTextField();
        fieldTamanho = new javax.swing.JTextField();

        itemMenuInserirPosicao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/imagens/add.png"))); // NOI18N
        itemMenuInserirPosicao.setText("posicao");
        itemMenuInserirPosicao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuInserirPosicaoActionPerformed(evt);
            }
        });
        menuPopUp.add(itemMenuInserirPosicao);

        itemMenuInserirDireita.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/imagens/add.png"))); // NOI18N
        itemMenuInserirDireita.setText("direita");
        itemMenuInserirDireita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuInserirDireitaActionPerformed(evt);
            }
        });
        menuPopUp.add(itemMenuInserirDireita);
        menuPopUp.add(separador);

        itemMenuRemover.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/imagens/delete.png"))); // NOI18N
        itemMenuRemover.setText("remover");
        itemMenuRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuRemoverActionPerformed(evt);
            }
        });
        menuPopUp.add(itemMenuRemover);

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Lista");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/imagens/listaP.png"))); // NOI18N

        painelDesenho.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                painelDesenhoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout painelDesenhoLayout = new javax.swing.GroupLayout(painelDesenho);
        painelDesenho.setLayout(painelDesenhoLayout);
        painelDesenhoLayout.setHorizontalGroup(
            painelDesenhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 379, Short.MAX_VALUE)
        );
        painelDesenhoLayout.setVerticalGroup(
            painelDesenhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        painelOperacoes.setBorder(javax.swing.BorderFactory.createTitledBorder("Operações"));

        labelValorInicio.setText("Valor do Início:");

        labelValorFim.setText("Valor do Fim:");

        labelRemoveuInicio.setText("Removeu do Início:");

        labelRemoveuFim.setText("Removeu do Fim:");

        fieldValorInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldValorInicioActionPerformed(evt);
            }
        });

        fieldValorFim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldValorFimActionPerformed(evt);
            }
        });

        fieldRemoveuInicio.setEditable(false);

        fieldRemoveuFim.setEditable(false);

        btnInserirInicio.setText("Inserir no Início");
        btnInserirInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInserirInicioActionPerformed(evt);
            }
        });

        btnInserirFim.setText("Inserir no Fim");
        btnInserirFim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInserirFimActionPerformed(evt);
            }
        });

        btnRemoverInicio.setText("Remover do Início");
        btnRemoverInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverInicioActionPerformed(evt);
            }
        });

        btnRemoverFim.setText("Remover do Fim");
        btnRemoverFim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverFimActionPerformed(evt);
            }
        });

        btnEsvaziar.setText("Esvaziar");
        btnEsvaziar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEsvaziarActionPerformed(evt);
            }
        });

        painelDados.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados da Estrutura"));

        labelInicio.setText("Início:");

        labelFim.setText("Fim:");

        labelTamanho.setText("Tamanho:");

        fieldInicio.setEditable(false);

        fieldFim.setEditable(false);

        fieldTamanho.setEditable(false);

        javax.swing.GroupLayout painelDadosLayout = new javax.swing.GroupLayout(painelDados);
        painelDados.setLayout(painelDadosLayout);
        painelDadosLayout.setHorizontalGroup(
            painelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelDadosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelFim)
                    .addComponent(labelTamanho)
                    .addComponent(labelInicio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fieldInicio, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                    .addComponent(fieldTamanho)
                    .addComponent(fieldFim))
                .addContainerGap())
        );
        painelDadosLayout.setVerticalGroup(
            painelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelDadosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelInicio)
                    .addComponent(fieldInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelFim)
                    .addComponent(fieldFim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTamanho)
                    .addComponent(fieldTamanho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout painelOperacoesLayout = new javax.swing.GroupLayout(painelOperacoes);
        painelOperacoes.setLayout(painelOperacoesLayout);
        painelOperacoesLayout.setHorizontalGroup(
            painelOperacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelOperacoesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelOperacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(painelDados, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelOperacoesLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(painelOperacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnRemoverFim, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnInserirInicio, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnInserirFim, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnRemoverInicio, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(painelOperacoesLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(painelOperacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(painelOperacoesLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnEsvaziar))
                            .addGroup(painelOperacoesLayout.createSequentialGroup()
                                .addGroup(painelOperacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(painelOperacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(labelValorInicio)
                                        .addComponent(labelValorFim)
                                        .addComponent(labelRemoveuInicio))
                                    .addComponent(labelRemoveuFim, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(painelOperacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(fieldValorInicio)
                                    .addComponent(fieldRemoveuFim)
                                    .addComponent(fieldValorFim)
                                    .addComponent(fieldRemoveuInicio))))))
                .addContainerGap())
        );
        painelOperacoesLayout.setVerticalGroup(
            painelOperacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelOperacoesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelOperacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelValorInicio)
                    .addComponent(fieldValorInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnInserirInicio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelOperacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldValorFim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelValorFim))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnInserirFim)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelOperacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldRemoveuInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelRemoveuInicio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRemoverInicio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelOperacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldRemoveuFim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelRemoveuFim))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRemoverFim)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEsvaziar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painelDados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(painelDesenho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painelOperacoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelOperacoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(painelDesenho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInserirInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInserirInicioActionPerformed
        inserirInicio();
    }//GEN-LAST:event_btnInserirInicioActionPerformed

    private void btnRemoverFimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverFimActionPerformed
        
        try {
            fieldRemoveuInicio.setText( "" );
            fieldRemoveuFim.setText( lista.removerFim() );
            if ( !lista.estaVazia() ) {
                fieldInicio.setText( lista.consultarInicio() );
                fieldFim.setText( lista.consultarFim() );
            } else {
                fieldInicio.setText( "vazio" );
                fieldFim.setText( "vazio" );
            }
            fieldTamanho.setText( String.valueOf( lista.getTamanho() ) );
            painelDesenho.repaint();
        } catch ( EmptyListException exc ) {
            fieldRemoveuInicio.setText( "" );
            fieldRemoveuFim.setText( "" );
            fieldInicio.setText( "vazio" );
            fieldFim.setText( "vazio" );
            fieldTamanho.setText( String.valueOf( lista.getTamanho() ) );
            painelDesenho.repaint();
            JOptionPane.showMessageDialog( this, "Lista vazia.", 
                    "Aviso", JOptionPane.WARNING_MESSAGE );
        }
        
    }//GEN-LAST:event_btnRemoverFimActionPerformed

    private void btnEsvaziarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEsvaziarActionPerformed
        
        lista.esvaziar();
        
        fieldValorInicio.setText( "" );
        fieldValorFim.setText( "" );
        fieldRemoveuInicio.setText( "" );
        fieldRemoveuFim.setText( "" );
        fieldInicio.setText( "vazio" );
        fieldFim.setText( "vazio" );
        fieldTamanho.setText( String.valueOf( lista.getTamanho() ) );
        
        painelDesenho.repaint();
        
    }//GEN-LAST:event_btnEsvaziarActionPerformed

    private void fieldValorInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldValorInicioActionPerformed
        inserirInicio();
    }//GEN-LAST:event_fieldValorInicioActionPerformed

    private void btnInserirFimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInserirFimActionPerformed
        inserirFim();
    }//GEN-LAST:event_btnInserirFimActionPerformed

    private void btnRemoverInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverInicioActionPerformed
        
        try {
            fieldRemoveuInicio.setText( lista.removerInicio() );
            fieldRemoveuFim.setText( "" );
            if ( !lista.estaVazia() ) {
                fieldInicio.setText( lista.consultarInicio() );
                fieldFim.setText( lista.consultarFim() );
            } else {
                fieldInicio.setText( "vazio" );
                fieldFim.setText( "vazio" );
            }
            fieldTamanho.setText( String.valueOf( lista.getTamanho() ) );
            painelDesenho.repaint();
        } catch ( EmptyListException exc ) {
            fieldRemoveuInicio.setText( "" );
            fieldRemoveuFim.setText( "" );
            fieldInicio.setText( "vazio" );
            fieldFim.setText( "vazio" );
            fieldTamanho.setText( String.valueOf( lista.getTamanho() ) );
            painelDesenho.repaint();
            JOptionPane.showMessageDialog( this, "Lista vazia.", 
                    "Aviso", JOptionPane.WARNING_MESSAGE );
        }
        
    }//GEN-LAST:event_btnRemoverInicioActionPerformed

    private void fieldValorFimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldValorFimActionPerformed
        inserirFim();
    }//GEN-LAST:event_fieldValorFimActionPerformed

    private void painelDesenhoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_painelDesenhoMouseClicked
        
        if ( SwingUtilities.isRightMouseButton( evt ) ) {

            List<AreaItemLista> areasItens = listaD.getAreasItens();

            for ( AreaItemLista item : areasItens ) {
                
                Point p = evt.getPoint();
                
                if ( item.getArea().contains( p ) ) {
                    
                    this.item = item;
                    
                    itemMenuInserirPosicao.setText( String.format( "Inserir Aqui (posicao: [%d])", item.getIndice() ) );
                    itemMenuInserirDireita.setText( String.format( "Inserir à Direita (posicao: [%d])", item.getIndice() + 1 ) );
                    itemMenuRemover.setText( String.format( "Remover (posicao: [%d])", item.getIndice() ) );
                    
                    menuPopUp.show( painelDesenho, p.x, p.y );
                    break;
                    
                }
            }
            
        }
        
        painelDesenho.repaint();
        
    }//GEN-LAST:event_painelDesenhoMouseClicked

    private void itemMenuInserirDireitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuInserirDireitaActionPerformed
        System.out.println( item.getIndice() + 1 );
        inserirEmIndice( item.getIndice() + 1 );
    }//GEN-LAST:event_itemMenuInserirDireitaActionPerformed

    private void itemMenuRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuRemoverActionPerformed
        
        String valor = lista.remover( item.getIndice() );
        
        fieldRemoveuInicio.setText( "" );
        fieldRemoveuFim.setText( "" );
        
        if ( !lista.estaVazia() ) {
            fieldInicio.setText( lista.consultarInicio() );
            fieldFim.setText( lista.consultarFim() );
        } else {
            fieldInicio.setText( "vazio" );
            fieldFim.setText( "vazio" );
        }
        
        fieldTamanho.setText( String.valueOf( lista.getTamanho() ) );
        painelDesenho.repaint();
        
        JOptionPane.showMessageDialog( painelDesenho, 
                String.format( "O item \"%s\" foi removido da posicao %d.",
                valor, item.getIndice() ), "Removido", 
                JOptionPane.INFORMATION_MESSAGE );
        
    }//GEN-LAST:event_itemMenuRemoverActionPerformed

    private void itemMenuInserirPosicaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuInserirPosicaoActionPerformed
        inserirEmIndice( item.getIndice() );
    }//GEN-LAST:event_itemMenuInserirPosicaoActionPerformed

    private void inserirEmIndice( int indice ) {
        
        String valor = JOptionPane.showInputDialog( painelDesenho, 
                String.format( "Valor a ser inserido na posição [%d]:", indice ) );

        if ( valor != null ) {

            lista.inserir( valor, indice );

            fieldValorInicio.setText( "" );
            fieldValorFim.setText( "" );
            fieldRemoveuInicio.setText( "" );
            fieldRemoveuFim.setText( "" );
            fieldInicio.setText( lista.consultarInicio() );
            fieldFim.setText( lista.consultarFim() );
            fieldTamanho.setText( String.valueOf( lista.getTamanho() ) );

            painelDesenho.repaint();
            item = null;

        }
        
    }
    
    private void inserirInicio() {
        
        lista.inserirInicio( fieldValorInicio.getText() );
        fieldValorInicio.setText( "" );
        fieldValorFim.setText( "" );
        fieldRemoveuInicio.setText( "" );
        fieldRemoveuFim.setText( "" );
        fieldInicio.setText( lista.consultarInicio() );
        fieldFim.setText( lista.consultarFim() );
        fieldTamanho.setText( String.valueOf( lista.getTamanho() ) );
        
        fieldValorInicio.requestFocus();
        
        painelDesenho.repaint();
        
    }
    
    private void inserirFim() {
        
        lista.inserirFim( fieldValorFim.getText() );
        fieldValorInicio.setText( "" );
        fieldValorFim.setText( "" );
        fieldRemoveuInicio.setText( "" );
        fieldRemoveuFim.setText( "" );
        fieldInicio.setText( lista.consultarInicio() );
        fieldFim.setText( lista.consultarFim() );
        fieldTamanho.setText( String.valueOf( lista.getTamanho() ) );
        
        fieldValorFim.requestFocus();
        
        painelDesenho.repaint();
        
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEsvaziar;
    private javax.swing.JButton btnInserirFim;
    private javax.swing.JButton btnInserirInicio;
    private javax.swing.JButton btnRemoverFim;
    private javax.swing.JButton btnRemoverInicio;
    private javax.swing.JTextField fieldFim;
    private javax.swing.JTextField fieldInicio;
    private javax.swing.JTextField fieldRemoveuFim;
    private javax.swing.JTextField fieldRemoveuInicio;
    private javax.swing.JTextField fieldTamanho;
    private javax.swing.JTextField fieldValorFim;
    private javax.swing.JTextField fieldValorInicio;
    private javax.swing.JMenuItem itemMenuInserirDireita;
    private javax.swing.JMenuItem itemMenuInserirPosicao;
    private javax.swing.JMenuItem itemMenuRemover;
    private javax.swing.JLabel labelFim;
    private javax.swing.JLabel labelInicio;
    private javax.swing.JLabel labelRemoveuFim;
    private javax.swing.JLabel labelRemoveuInicio;
    private javax.swing.JLabel labelTamanho;
    private javax.swing.JLabel labelValorFim;
    private javax.swing.JLabel labelValorInicio;
    private javax.swing.JPopupMenu menuPopUp;
    private javax.swing.JPanel painelDados;
    private javax.swing.JPanel painelDesenho;
    private javax.swing.JPanel painelOperacoes;
    private javax.swing.JPopupMenu.Separator separador;
    // End of variables declaration//GEN-END:variables
}
