/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package gui;

import estruturas.Pilha;
import gui.desenho.PainelDesenho;
import gui.desenho.estruturas.PilhaDesenhavel;
import java.util.EmptyStackException;
import javax.swing.JOptionPane;

/**
 * Janela para a simulação de pilhas.
 * 
 * @author David Buzatto
 */
public class IFPilha extends javax.swing.JInternalFrame {

    private Pilha<String> pilha;
    private PilhaDesenhavel pilhaD;
    
    /**
     * Creates new form IFPilha
     */
    public IFPilha() {
        
        pilha = new Pilha<>();
        pilhaD = new PilhaDesenhavel( pilha );
        
        initComponents();
        setVisible( true );
        
        pilhaD.setPainel( painelDesenho );
        
        fieldTopo.setText( "vazio" );
        fieldTamanho.setText( String.valueOf( pilha.getTamanho() ) );
        painelDesenho.repaint();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings( "unchecked" )
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelDesenho = new PainelDesenho( pilhaD );
        painelOperacoes = new javax.swing.JPanel();
        labelValor = new javax.swing.JLabel();
        labelDesempilhou = new javax.swing.JLabel();
        fieldValor = new javax.swing.JTextField();
        fieldDesempilhou = new javax.swing.JTextField();
        btnEmpilhar = new javax.swing.JButton();
        btnDesempilhar = new javax.swing.JButton();
        btnEsvaziar = new javax.swing.JButton();
        painelDados = new javax.swing.JPanel();
        labelTopo = new javax.swing.JLabel();
        labelTamanho = new javax.swing.JLabel();
        fieldTopo = new javax.swing.JTextField();
        fieldTamanho = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Pilha");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/imagens/pilhaP.png"))); // NOI18N

        javax.swing.GroupLayout painelDesenhoLayout = new javax.swing.GroupLayout(painelDesenho);
        painelDesenho.setLayout(painelDesenhoLayout);
        painelDesenhoLayout.setHorizontalGroup(
            painelDesenhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 342, Short.MAX_VALUE)
        );
        painelDesenhoLayout.setVerticalGroup(
            painelDesenhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        painelOperacoes.setBorder(javax.swing.BorderFactory.createTitledBorder("Operações"));

        labelValor.setText("Valor:");

        labelDesempilhou.setText("Desempilhou:");

        fieldValor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldValorActionPerformed(evt);
            }
        });

        fieldDesempilhou.setEditable(false);

        btnEmpilhar.setText("Empilhar");
        btnEmpilhar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmpilharActionPerformed(evt);
            }
        });

        btnDesempilhar.setText("Desempilhar");
        btnDesempilhar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDesempilharActionPerformed(evt);
            }
        });

        btnEsvaziar.setText("Esvaziar");
        btnEsvaziar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEsvaziarActionPerformed(evt);
            }
        });

        painelDados.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados da Estrutura"));

        labelTopo.setText("Topo:");

        labelTamanho.setText("Tamanho:");

        fieldTopo.setEditable(false);

        fieldTamanho.setEditable(false);

        javax.swing.GroupLayout painelDadosLayout = new javax.swing.GroupLayout(painelDados);
        painelDados.setLayout(painelDadosLayout);
        painelDadosLayout.setHorizontalGroup(
            painelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelDadosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelTamanho)
                    .addComponent(labelTopo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fieldTopo, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                    .addComponent(fieldTamanho))
                .addContainerGap())
        );
        painelDadosLayout.setVerticalGroup(
            painelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelDadosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTopo)
                    .addComponent(fieldTopo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTamanho)
                    .addComponent(fieldTamanho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(118, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout painelOperacoesLayout = new javax.swing.GroupLayout(painelOperacoes);
        painelOperacoes.setLayout(painelOperacoesLayout);
        painelOperacoesLayout.setHorizontalGroup(
            painelOperacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelOperacoesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelOperacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelOperacoesLayout.createSequentialGroup()
                        .addGroup(painelOperacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelDesempilhou)
                            .addComponent(labelValor))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(painelOperacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fieldValor)
                            .addComponent(fieldDesempilhou)))
                    .addComponent(painelDados, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelOperacoesLayout.createSequentialGroup()
                        .addGap(0, 71, Short.MAX_VALUE)
                        .addGroup(painelOperacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnEmpilhar, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnDesempilhar, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnEsvaziar, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        painelOperacoesLayout.setVerticalGroup(
            painelOperacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelOperacoesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelOperacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelValor)
                    .addComponent(fieldValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEmpilhar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelOperacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDesempilhou)
                    .addComponent(fieldDesempilhou, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDesempilhar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEsvaziar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painelDados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(painelDesenho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painelOperacoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelOperacoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(painelDesenho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEmpilharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmpilharActionPerformed
        empilhar();
    }//GEN-LAST:event_btnEmpilharActionPerformed

    private void btnDesempilharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDesempilharActionPerformed
        
        try {
            fieldDesempilhou.setText( pilha.desempilhar() );
            if ( !pilha.estaVazia() ) {
                fieldTopo.setText( pilha.consultarTopo() );
            } else {
                fieldTopo.setText( "vazio" );
            }
            fieldTamanho.setText( String.valueOf( pilha.getTamanho() ) );
            painelDesenho.repaint();
        } catch ( EmptyStackException exc ) {
            fieldDesempilhou.setText( "" );
            fieldTopo.setText( "vazio" );
            fieldTamanho.setText( String.valueOf( pilha.getTamanho() ) );
            painelDesenho.repaint();
            JOptionPane.showMessageDialog( this, "Pilha vazia.", 
                    "Aviso", JOptionPane.WARNING_MESSAGE );
        }
        
    }//GEN-LAST:event_btnDesempilharActionPerformed

    private void btnEsvaziarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEsvaziarActionPerformed
        
        pilha.esvaziar();
        fieldValor.setText( "" );
        fieldDesempilhou.setText( "" );
        fieldTopo.setText( "vazio" );
        fieldTamanho.setText( String.valueOf( pilha.getTamanho() ) );
        
        painelDesenho.repaint();
        
    }//GEN-LAST:event_btnEsvaziarActionPerformed

    private void fieldValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldValorActionPerformed
        empilhar();
    }//GEN-LAST:event_fieldValorActionPerformed

    private void empilhar() {
        
        pilha.empilhar( fieldValor.getText() );
        fieldValor.setText( "" );
        fieldDesempilhou.setText( "" );
        fieldTopo.setText( pilha.consultarTopo() );
        fieldTamanho.setText( String.valueOf( pilha.getTamanho() ) );
        
        fieldValor.requestFocus();
        
        painelDesenho.repaint();
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDesempilhar;
    private javax.swing.JButton btnEmpilhar;
    private javax.swing.JButton btnEsvaziar;
    private javax.swing.JTextField fieldDesempilhou;
    private javax.swing.JTextField fieldTamanho;
    private javax.swing.JTextField fieldTopo;
    private javax.swing.JTextField fieldValor;
    private javax.swing.JLabel labelDesempilhou;
    private javax.swing.JLabel labelTamanho;
    private javax.swing.JLabel labelTopo;
    private javax.swing.JLabel labelValor;
    private javax.swing.JPanel painelDados;
    private javax.swing.JPanel painelDesenho;
    private javax.swing.JPanel painelOperacoes;
    // End of variables declaration//GEN-END:variables
}
